---
- name: Check if reboot is needed
    command: needs-restarting -r
    changed_when: false
    register: reboot
    listen: Check Reboot

- name: Display the results
  debug:
    var: reboot
# - name: Reboot the host if required
#   reboot:
#     msg: "apt upgrade required a reboot"
#   listen: Check Reboot
#   when: reboot.