---
- block:
  - name: Check if reboot file exists
    stat:
      path: /var/run/reboot-required
    register: reboot

  - name: Reboot the host if required
    reboot:
      msg: "apt upgrade required a reboot"
    when:
      - reboot.stat.exists
  become: true