---
- name: Reboot Tasks Debian
  become: true
  block:
    - name: Check if reboot file exists
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot

    - name: Display the reboot status
      ansible.builtin.debug:
        var: reboot.stat

    - name: Reboot the host if required
      ansible.builtin.reboot:
        msg: "apt upgrade required a reboot"
      when:
        - reboot.stat.exists
