---
# Handler for Debian and derivative distros
- name: Reboot handler for debian
  listen: check reboot debian
  when: ansible_os_family == "Debian"
  become: true

# Handler for Redhat and derivative distros
- name: Reboot handler for redhat
  listen: check reboot redhat
  when: ansible_os_family == "RedHat"
  become: true
