---
# Handler for Debian and derivative distros
- name: Check reboot debian
  ansible.builtin.include_tasks: "check-debian-reboot.yml"
  when: ansible_os_family == "Debian"

# Handler for Redhat and derivative distros
- name: Check reboot redhat
  ansible.builtin.include_tasks: "check-redhat-reboot.yml"
  when: ansible_os_family == "RedHat"
