---
# Handler for Debian and derivative distros
- name: check reboot debian
  include_tasks: "check-debian-reboot.yml"
  when: ansible_os_family == "Debian"

# Handler for Redhat and derivative distros
- name: check reboot redhat
  include_tasks: "check-redhat-reboot.yml"
  when: ansible_os_family == "RedHat"
